### ISSUE TITLE
Markdown links are broken on reflow

### ISSUE THREAD

**Issue by lee-dohm** [atom/autoflow#11]
See the Discuss topic that led to this: http://discuss.atom.io/t/make-reflow-selection-markdown-aware/10995

Markdown hyperlinks can be broken by inserting a line break in between the label and the link address, like so:

![screen shot 2014-07-19 at 5 05 43 pm](https://cloud.githubusercontent.com/assets/1038121/3636138/1ee3f3ee-0fa3-11e4-8ab3-7907411df46d.png)

**Comment by jonleung** [comment]
:+1:

**Comment by daviwil** [comment]
This issue was moved to atom/atom#18031
