### ISSUE TITLE
Latex comments broken on reflow selection

### ISSUE THREAD

**Issue by fbrundu** [atom/autoflow#12]
Hi,
I have not a gif but this issue is easily reproducible. 

When I comment a long line with Latex (comment starts with `%`) and then run reflow selection, the comment is truncated (reflown) but only the first part is commented. The following new lines are not commented.

I tested only Latex but maybe this issue affects other languages as well.

Thanks

**Comment by daviwil** [comment]
This issue was moved to atom/atom#18030
