### ISSUE TITLE
[Windows] alt-ctrl-q -> autoflow:reflow-selection

### ISSUE THREAD

**Issue by philipgiuliani** [atom/autoflow#13]
In windows <key>alt + ctrl + q</key> or <key>altgr + q</key> should be native and create a `@`.
It runs `autoflow:reflow-selection` instead of beeing native!

Its not possible to create a `@` at the moment. I had to disable the package.

**Comment by dogancelik** [comment]
I have the same problem. <kbd>Altgr-q</kbd> is the only way to type `@` in Turkish locale on Windows.

**Comment by lee-dohm** [comment]
This is a duplicate of atom/atom-keymap#35. Please subscribe there for updates.

I'm going to close this as duplicate.

**Comment by hiroyukims** [comment]
How to I disable reflow-selection ?
