### ISSUE TITLE
key-binding vs hungarian keyboard

### ISSUE THREAD

**Issue by kicsikrumpli** [atom/autoflow#16]
on hungarian keyboard some special characters are accessible through the key combination altGr-<key>, which is the equivalent of Ctrl-Alt-<key>. Autoreflow is mapped to Ctrl-Alt-q, which is the key combination required for the \ backslash chacter.

**Comment by mnquintana** [comment]
I think this is blocked on https://github.com/atom/atom-keymap/issues/35

**Comment by 50Wliu** [comment]
Fixed.
