### ISSUE TITLE
Sometimes reflow gives unexpected results

### ISSUE THREAD

**Issue by fbrundu** [atom/autoflow#17]
With some paragraphs:

    Example paragraph hahahah akjfalk ahahahah lkakj lkjaoi lkajlkj
    adflkjalfk lkajl kj lk  jj jajal ajajalkajofilajiel
    ahahah

I get unexpected results:

    Example paragraph hahahah akjfalk ahahahah lkakj lkjaoi lkajlkj
     adflkjalfk
    lkajl kj lk  jj jajal ajajalkajofilajiel
     ahahah
 
After working on it, I think that lines which begin with a space mean that they can be joined with the previous line. So, the correct reflow for the example is:

    Example paragraph hahahah akjfalk ahahahah lkakj lkjaoi lkajlkj adflkjalfk
    lkajl kj lk  jj jajal ajajalkajofilajiel ahahah
 
This problem appears sometimes. I did not figure out why reflow sometimes works well, sometimes not. I am using autoflow 0.18.0, atom 0.136.0, on Ubuntu 14.04.

Thanks.

**Comment by nscaife** [comment]
I often run into this as well.  As a comparison, vim with `set textwidth=80` produces the following when reflowing:

    Example paragraph hahahah akjfalk ahahahah lkakj lkjaoi lkajlkj adflkjalfk lkajl
    kj lk  jj jajal ajajalkajofilajiel ahahah

**Comment by crscardellino** [comment]
I am having a similar problem. If I have a one line text, it reflows just right:
> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac molestie erat, commodo convallis mi.

becomes:
> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac molestie erat,
> commodo convallis mi.

However, the next example:
> Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
> Nam ac molestie erat, commodo convallis mi.

becomes: 
> Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
>  Nam ac molestie erat,
> commodo convallis mi.

There is a explicit space before "Nam"

**Comment by Dangthrimble** [comment]
Reflow also doesn't work properly if a portion of the paragraph has been selected.

Further, I have a problem with the following Markdown from the Rust documentation:

````
The second point is the `println!()` part. This is calling a Rust
[macro][macro], which is how metaprogramming is done in Rust. If it were a
function instead, it would look like this: `println()`. For our purposes, we
don’t need to worry about this difference. Just know that sometimes, we’ll see a `!`,
and that means that we’re calling a macro instead of a normal function. Rust
implements `println!` as a macro rather than a function for good reasons, but
that's an advanced topic. One last thing to mention: Rust’s macros are
significantly different from C macros, if we’ve used those. Don’t be scared of
using macros. We’ll get to the details eventually, we’ll just have to take it on
trust for now.
````

The fourth line should wrap after "we'll see a".

I'm using autoflow 0.25.0 and atom 1.0.3 on Win10 x64.
