### ISSUE TITLE
Not working with Russian

### ISSUE THREAD

**Issue by lazutkin** [atom/autoflow#28]
Doesn't work with Russian and I think with any other lang that doesn't matched by `\w` regexp [here](https://github.com/atom/autoflow/blob/8955a28677368a9a4ec12ba650613fb914537a19/lib/autoflow.coffee#L57)

**Comment by lee-dohm** [comment]
Can you paste us some sample text that doesn't work so that we can reproduce this on our end? :grinning:

**Comment by lazutkin** [comment]
Sure,

```
Мосгорсуд оставил в силе решение Замоскворецкого суда российской столицы, отказавшегося допустить до выборов "Партию прогресса" оппозиционера Алексея Навального.
```

**Comment by lee-dohm** [comment]
Confirmed using Atom v0.202.0-7b3a648 on Mac OS X 10.10.3.

**Comment by kevinsawicki** [comment]
#32 was cherry-picked to master, closing this out.
