### ISSUE TITLE
German Windows Keyboard

### ISSUE THREAD

**Issue by BlaM** [atom/autoflow#30]
Nor sure for other OS, but in Windows / German keyboard layout AltGr + Q (equals "Strg + Alt + Q") is used to type the at-sign ("@"). So - as long as I don't change the setup of autoflow - each time I want to get an "@" the current file is destroyed.

("AltGr" is a known issue in Atom: https://github.com/atom/atom-keymap/issues/35 )

**Comment by lee-dohm** [comment]
I'm not sure what the issue is here beyond what is already described in atom/atom-keymap#35?

**Comment by BlaM** [comment]
Mainly that the plug-in defaults to the very common combination of keys that totally breaks usability of the editor for all German users - especially for first time users who are unaware of the keyboard issues. 

Not sure if there is a sensible solution for this plug-in. My solution was to disable it.

**Comment by kevinsawicki** [comment]
I believe this is a duplicate of #16
