### ISSUE TITLE
Reflow Selection sometimes inserts an unnecessary space at the beginning of the first non-blank line

### ISSUE THREAD

**Issue by WalterGR** [atom/autoflow#42]
Atom 1.3.2 on OS X 10.10.5.

Repro:

1.  Type the following.  Assume the second line is long enough that it will be reflowed.  The pipes shouldn't be typed and simply indicate the beginning of the line.

        | 
        |This is a test.
        | 
        |This is a test.  This is a test.  This is a test.  This is a test.  This is a test.  This is a test.  This is a test.

2.  Select the typed text _as well as_ the blank line above the first line.

3.  Perform Reflow Selection.

Expected:

    | 
    |This is a test.
    | 
    |This is a test.  This is a test.  This is a test.  This is a test.  This is a
    |test.  This is a test.  This is a test.

Actual:

    | 
    | This is a test.
    | 
    |This is a test.  This is a test.  This is a test.  This is a test.  This is a
    |test.  This is a test.  This is a test.

Notice that a space was added to the beginning of the first non-blank line for no reason.

This doesn't repro if you select the text and don't select the blank line before the first line.

**Comment by WalterGR** [comment]
(Added Atom and OS X versions to description.)

**Comment by amytruong** [comment]
Was able to reproduce @lee-dohm

**Comment by amytruong** [comment]
Thanks for the details @WalterGR :smile:

**Comment by glv** [comment]
FYI: my pull request https://github.com/atom/autoflow/pull/40 fixes this problem.

**Comment by joshaber** [comment]
#40 landed.
