### ISSUE TITLE
Conflicts with adding an @ sign into the editor

### ISSUE THREAD

**Issue by DorianVasco** [atom/autoflow#44]
Even if the key binding is set to ctrl+alt+q, it still blocks the standard short cut for adding an @ sign on a German Windows machine:
AltGr+Q

**Comment by 50Wliu** [comment]
This is actually caused by atom/atom-keymap#35 - feel free to subscribe there for updates.  As a workaround you can try installing the [keyboard-localization](https://atom.io/packages/keyboard-localization) package.
