### ISSUE TITLE
Problem with German keyboards under Windows

### ISSUE THREAD

**Issue by derwaldgeist** [atom/autoflow#48]
On German keyboards under Windows, the default shortcut is the same that is used for the @ sign (AltGr-Q). This causes unwanted formatting and prevents usage of the @ sign, which is quite annoying.

**Comment by 50Wliu** [comment]
This is a duplicate of atom/atom-keymap#35 - feel free to subscribe there for updates.

**Comment by derwaldgeist** [comment]
OK, thanks for the info.
