### ISSUE TITLE
Add support for .editorconfig file

### ISSUE THREAD

**Issue by terrycloth** [atom/autoflow#58]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[EditorConfig](http://editorconfig.org/) is an attempt at standardizing certain configurations across text/code editors, to help keep things consistent, no matter who is editing the file or with what program. You can configure [settings](https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties) for a whole project, a directory, or specific files matched using globbing patterns, with rules set in standard INI format.

In particular, I think it would be helpful if Autoflow followed the `max_line_length` directive, which defines what *should* be the maximum number of characters per line. EditorConfig currently only uses the value here to set the placement of a visual text wrapping guide --- i.e., a *hint*, rather than forcing hard-wrap. However, I think "maximum line length" is semantically related enough that it would make sense for Autoflow to use this directive when determining how to rewrap text in the current context.

### Versions

* Fedora 25 Workstation x86_64
* Atom 1.15.0
* Autoflow 0.29.0
* Electron 1.3.13
* Chrome 52.0.2743.82
* Node 6.5.0
* apm  1.13.0
* npm  3.10.10
* node 6.9.5
* python 2.7.13
* git 2.9.3

**Comment by daviwil** [comment]
This issue was moved to atom/atom#18019
