### ISSUE TITLE
"Auto-reflow" on editing

### ISSUE THREAD

**Issue by ahti** [atom/autoflow#7]
I think it might be useful to have an option to reflow paragraphs after every edit (typing, insertion, deletion, ...), so the user doesn't need to remember to reflow his buffer after writing.

Because this might not make sense for every kind of document, I think it would be reasonable to allow the user to select on which document kinds (identified by their grammar) this feature should be enabled.

**Comment by wmayner** [comment]
:+1:

**Comment by levity** [comment]
I like this idea too; any chance of it making it into a new release?

**Comment by daviwil** [comment]
This issue was moved to atom/atom#18033
